# Base stage for shared environment setup
FROM node:14-alpine as base
WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm install
COPY ./frontend .

# Development stage
FROM base as development
CMD ["npm", "run", "dev"]

# Production stage
FROM base as production
RUN npm run build
CMD ["npm", "start"]
