version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: development # Change to `production` for production
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings.dev # Change as needed
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: development # Change to `production` for production
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
